# Register this repo at https://whitewater.ibm.com/tools/travis

# We don't know and don't care about the starter language, but use npm and node inside some scripts:
language: node_js

# Specify a level for stability.
node_js:
  - '5.5.0'

cache:
  directories:
    - "node_modules"
    - "bmd-devops-pipeline"

# Nothing special to install since we're just verifying compatibility of this repo with the
# developer experience infrastructure.
install: true

# Clone the repository that has the smart script for validating this repo against the registry
# microservice (which itself validates against scaffolder, therefore Yeoman and SDKGen microservices).
# It's the kitchen sink of validation!
before_script:
  - ls ~/.ssh
  - openssl aes-256-cbc -K $encrypted_8fce584fd168_key -iv $encrypted_8fce584fd168_iv -in ".travis/github_deploy_key.enc" -out "custom-SSH-file" -d
  - cp custom-SSH-file ~/.ssh/
  - chmod 600 "custom-SSH-file" && printf "%s\n" "Host github.ibm.com" "  IdentityFile custom-SSH-file" "  HostName github.ibm.com" "  LogLevel ERROR" >> ~/.ssh/config
  - cat .git/config
  - git config user.name "mamoon.raja"
  - git config user.email "mamoon.raja@ibm.com"
  - git clone -b v1 git@github.ibm.com:bluemix-mobile-services/bmd-devops-pipeline.git

# Run a dry-run registration for pull requests, and a real registration for pushes.
# register-starter.sh is smart!
script:
  - npm run lint
  - npm run codecov
  - ./bmd-devops-pipeline/scripts/register-starter.sh $TRAVIS_BRANCH

# Pull request builds and push builds only run when the target branch is one of these:
branches:
  only:
    - master
    - stage1
    - development
